name: "CI: lint (super-linter)"

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false

      - name: Super-Linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MULTI_STATUS: false
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
